name: build
on:
  pull_request:
  push:
    branches: master
jobs:
  build:
    runs-on: nix
    strategy:
      matrix:
        arch: [x86_64-linux]
        flavor: [static, shared]
    steps:
      - uses: actions/checkout@v3
      - run: nix build --print-out-paths -L .#packages.${{ matrix.arch }}.${{ matrix.flavor }} > out-paths
      - run: >-
          gcroot=$(echo ${{ github.repository }} | sed 's/\//-/g').${{ matrix.arch }}.${{ matrix.flavor }};
          ln -s $(tail -n 1 out-paths) /nix/var/nix/gcroots/per-user/$(whoami)/$gcroot
