name: checks
on:
  pull_request:
  push:
    branches: master
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: nix
    strategy:
      matrix:
        arch: [x86_64-linux]
        flavor: [shared, static]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test-mk-gerbil-package
        run: >-
          cd test;
          nix flake lock;
          nix develop .#devShells.${{ matrix.arch }}.gerbil-${{ matrix.flavor }} -L --command
          bash -xec "gxi -e '(import :mk-gerbil-package/hello)' -e '(displayln words)'"
      - name: test-openssl
        run: >-
          cd test;
          nix flake lock;
          nix develop .#devShells.${{ matrix.arch }}.gerbil-${{ matrix.flavor }} -L --command
          bash -xec "gxi -e '(import :std/net/request)'"
      - name: test-sqlite
        run: >-
          cd test;
          nix flake lock;
          nix develop .#devShells.${{ matrix.arch }}.gerbil-${{ matrix.flavor }} -L --command
          bash -xec "gxi -e '(import :std/db/dbi :std/db/sqlite)' -e '(sql-connect sqlite-open \":memory:\")'"
