name: test
on:
  pull_request:
  push:
    branches: master
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: nix
    strategy:
      matrix:
        arch: [x86_64-linux]
        flavor: [static]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test-mk-gerbil-package
        run: >-
          cd test;
          nix flake lock;
          nix develop .#devShells.${{ matrix.arch }}.${{ matrix.flavor }} -L --command
          bash -ec "gxi -e '(import :mk-gerbil-package/hello)' -e '(displayln words)'"
